version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: seguradora-postgres
    environment:
      POSTGRES_DB: seguradora_orders
      POSTGRES_USER: seguradora_user
      POSTGRES_PASSWORD: seguradora_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    networks:
      - seguradora-network

  # Fraud API Mock (WireMock)
  fraud-api-mock:
    image: wiremock/wiremock:2.35.0
    container_name: seguradora-fraud-api
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings
      - ./wiremock/__files:/home/wiremock/__files
    command: ["--global-response-templating", "--verbose"]
    networks:
      - seguradora-network

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: seguradora-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - seguradora-network

  # Kafka
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: seguradora-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - seguradora-network

  # Application
  # ms-order:
  #   build: .
  #   container_name: seguradora-ms-order
  #   depends_on:
  #     - postgres
  #     - kafka
  #     - fraud-api-mock
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     SPRING_PROFILES_ACTIVE: docker
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/seguradora_orders
  #     SPRING_DATASOURCE_USERNAME: seguradora_user
  #     SPRING_DATASOURCE_PASSWORD: seguradora_pass
  #     SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  #     FRAUD_API_BASE_URL: http://fraud-api-mock:8080
  #     # Simulador de serviços externos habilitado
  #     APP_SIMULATOR_ENABLED: 'true'
  #   networks:
  #     - seguradora-network

volumes:
  postgres_data:
  kafka_data:

networks:
  seguradora-network:
    driver: bridge
