spring:
  application:
    name: ms-order

  datasource:
    url: jdbc:postgresql://localhost:5432/seguradora_orders
    username: seguradora_user
    password: seguradora_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3

app:
  fraud-api:
    url: http://fraud-api-mock:8080/api/v1

  # Configurações do Simulador de Serviços Externos
  simulator:
    enabled: false  # Habilita/desabilita o simulador
    fixed-payment-status: null      # APPROVED ou REJECTED (null = usar lógica aleatória)
    fixed-subscription-status: null # APPROVED ou REJECTED (null = usar lógica aleatória)
    payment-delay-seconds: 2        # Delay em segundos para simular processamento de pagamento
    subscription-delay-seconds: 3   # Delay em segundos para simular análise de subscrição

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.seguradora.msorder: INFO
    org.springframework.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
